baseURL: https://ariascosb.com/ #cambiar a ariascosb.com, cuando compre un dominio
languageCode: es
defaultContentLanguage: es
title: ariascosb #Titulo de la pestaña del navegador web

theme: PaperMod_My
#description: "Un blog sobre Programación, Ingeniería y Matemáticas aplicadas"

#De aqui hacia abajo copia del tema

paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#Google Analytics
googleAnalytics: G-R34YZRH37C

permalinks:
  posts: /:year/:month/:slug/

minify:
    disableXML: true
    minifyOutput: true

#Habilitar la busqueda dentro del blog
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ariascosb
    description: "Un blog sobre Programación, Ingeniería y Matemáticas aplicadas"
    keywords: [Python, R, Rstudio, Linux, ariascosb, Andres Riascos B., Andres Riascos]
    author: Andres Riascos B.
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false #mostrar tabla de contenido
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"
        #safari_pinned_tab:  "/static/img/safari-pinned-tab.svg"

    label:
        text: "Inicio"
        #Logo
        #icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ariascosb
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Bienvenid@ \U0001F44B"
        Content: Un blog sobre ingeniería, matemáticas aplicadas y programación


    socialIcons:
        - name: twitter
          url: "https://twitter.com/ariascosb"
        #- name: linkedin
        #  url: "https://www.linkedin.com/in/ariascosb/"
        - name: github
          url: "https://github.com/ariascosb"

    #analytics:
    #    google:
    #        SiteVerificationTag: "XYZabc"
    #    bing:
    #        SiteVerificationTag: "XYZabc"
    #    yandex:
    #        SiteVerificationTag: "XYZabc"

    #Coer es para tener una portada de imagen en cada post.
    #cover:
    #    hidden: true # hide everywhere but not in structured data
    #    hiddenInList: true # hide on list pages and home
    #    hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/ariascosb/ariascosb_blog/blob/main/content/"
        Text: "Sugerir cambios" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

#Pestañas del blog
menu:
    main:
        - identifier: Categorias
          name: Categorias
          url: /categories/
          weight: 40
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 10
        - identifier: archivo
          name: Archivo
          url: /archivo/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30



# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
     highlight:
         # anchorLineNos: true
         codeFences: true
         guessSyntax: true
         lineNos: false #añade una linea contador a cada linea de codigo
         # noClasses: false
         style: nord
         #swapoff
         #monokai